[package]
name = "svn_auth_saver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.18"
msgbox = "0.6.0"
structopt = "0.3.2"
anyhow = "1.0.36"
thiserror = "1.0.22"